### ISSUE TITLE
Is this email still valid hpcpack@microsoft.com ?

### ISSUE THREAD

**Issue by MichelFontaine75** [Azure/hpcpack#6]
Is this email still valid hpcpack@microsoft.com because per my Technical Account Manager at Microsoft it is not and this is the method I was using to reach the HPC Pack Team ?  I have 2 questions pending that I forwarded to my TAM because I didn't got any feedback to my last 2 emails at hpcpack@microsoft.com

**Comment by sunbinzhu** [comment]
Yes, the email is still valid.
