### ISSUE TITLE
Node Metrics via RESTful API

### ISSUE THREAD

**Issue by jedugan** [Azure/hpcpack#7]
#### Feature Request Description
We have an integration with MHPC that uses the REST API, and we would like to be able to get performance metrics for a node (specifically CPU%, memory usage, and tasks running) via this API.

#### Describe Preferred Solution
A REST API endpoint for getting performance metric values for all nodes.

#### Describe Alternatives Considered
Node metrics are available from MHPC PowerShell via the Get-HpcMetricValue cmdlet, but this is not a feasible solution for our environment.

#### Additional Context
None.

**Comment by coin8086** [comment]
Hi @jedugan, HPC Pack 2019 provides a new web portal, in which the metrics like CPU, memory and tasks etc., are shown as in the admin console. This implies that it has a set of REST API for the metrics. You can find the API spec at:

https://github.com/Azure/hpcpack-rest-api-spec/blob/2019/src/hpcpack.yaml 

and take the portal code as an example of usage:

 https://github.com/Azure/hpcpack-web-portal

However, please note that the API is not officially published and its purpose is for the portal use. So use it at your own risk.

**Comment by jedugan** [comment]
Great, thanks! I'll take a look at the 2019 API.
